/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ETP.ExamTakingSystem;

import com.ETP.ExamTakingSystem.UI.ExamManagement;
import com.ETP.ExamTakingSystem.UI.StudentManagment;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application{   

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Admin Dashboard");

        Label welcomeLabel = new Label("Welcome, Admin!");

        Button manageStudentsBtn = new Button("Manage Students");
        Button manageExamsBtn = new Button("Manage Exams");
        Button logoutBtn = new Button("Logout");

        manageStudentsBtn.setOnAction(e -> StudentManagment.showWindow());
        manageExamsBtn.setOnAction(e -> ExamManagement.showWindow());
        logoutBtn.setOnAction(e -> primaryStage.close());

        VBox layout = new VBox(10);
        layout.setPadding(new Insets(20));
        layout.getChildren().addAll(welcomeLabel, manageStudentsBtn, manageExamsBtn, logoutBtn);
        layout.setAlignment(Pos.CENTER);
        

        Scene scene = new Scene(layout, 1920, 1080);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}



